version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped
  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped